### PR TITLE
Deprecate in favour of updated upstream

### PR DESCRIPTION
**Pull request by dougneal**
This repo could also be deleted.

### CODE REVIEW

**Comment by philandstuff** [comment]
let's just delete the repo. I'll do that now

**Comment by philandstuff** [comment]
actually.. do we know if anyone is still using this repo directly rather than upstream?

**Comment by dougneal** [comment]
https://github.com/search?q=%22alphagov%2Fpuppet-apparmor%22&type=Code shows a couple of uses in https://github.com/alphagov/govuk_mirror-puppet  and in https://github.com/alphagov/govuk_redirector-puppet ...

**Comment by philandstuff** [comment]
I'll hold off deleting then, but i can archive it at least

**Pull request closed without merging**
